global:
  resolve_timeout: 30s

route:
  receiver: 'webhook-receiver'
  group_by: ['alertname']
  group_wait: 3s
  group_interval: 1m
  repeat_interval: 3s 

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://10.1.29.17:1103/notify'
        send_resolved: true