global:
  resolve_timeout: 5m

route:
  receiver: 'webhook-receiver'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://areadiv.com/monitoring/index.php'
        send_resolved: true
