global:
  resolve_timeout: 30s

route:
  receiver: 'webhook-receiver'
  group_by: ['alertname']
  group_wait: 3s
  group_interval: 1m
  repeat_interval: 24h  # Set to a long duration to avoid frequent repeats

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://areadiv.com/monitoring/index.php?host={{ .CommonLabels.instance }}&alert={{ .CommonLabels.alertname }}&status={{ .CommonLabels.status }}&severity={{ .CommonLabels.severity }}&summary={{ .CommonAnnotations.summary }}&description={{ .CommonAnnotations.description }}'
        send_resolved: true
