global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'group', 'instance', 'job', 'service', 'severity']
  group_wait: 30s
  group_interval: 30s
  repeat_interval: 30s
  receiver: 'line-alerts'

receivers:
- name: 'line-alerts'
  webhook_configs:
  - url: 'http://localhost/anuwad/'
    send_resolved: true


    
