global:
  resolve_timeout: 30s

route:
  receiver: 'webhook-receiver'
  group_by: ['alertname']
  group_wait: 3s
  group_interval: 1m
  repeat_interval: 1m

receivers:
  - name: 'webhook-receiver'
    webhook_configs:
      - url: 'http://areadiv.com/monitoring/index.php'
        send_resolved: true
