version: "3.8"
networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}
  grafana_data: {}

services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring

  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - "3000:3000"
    networks:
      - monitoring

  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    command: 
      - '--config.file=/alertmanager/alertmanager.yml'
    networks:
      - monitoring
  
  line-notify:
    image: line-notify:latest
    container_name: line-notify
    ports:
      - "1103:3000"
    volumes:
      - ./line-notify:/app
    networks:
      - monitoring
  
  example-nodejs-app:
    image: node-app:latest
    container_name: example-nodejs-app
    ports:
      - "4723:3000"
    volumes:
      - ./example-nodejs-app:/app
    networks:
      - monitoring

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    container_name: blackbox-exporter
    ports:
      - "9115:9115"
    networks:
      - monitoring
