version: "2.1"
networks:
  monitoring:
    driver: bridge
volumes:
  prometheus_data: {}
  grafana_data: {}
services:
  prometheus:
    image: prom/prometheus:v2.20.1
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    ports:
      - 9095:9090
    expose:
      - 9095
    networks:
      - monitoring
  grafana:
    image: grafana/grafana:7.1.5
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    ports:
      - 3000:3000
    expose:
      - 3000
    networks:
      - monitoring
  example-nodejs-app:
    build:
      context: example-nodejs-app
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - monitoring
  example-nodejs-app2: 
    build:
      context: example-nodejs-app2
    ports:
      - 8081:8080
    expose:
      - 8080 
    networks:
      - monitoring
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    volumes:
      - ./alertmanager/alertmanager.yml:/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    command: 
      - '--config.file=/alertmanager/alertmanager.yml'
    expose:
      - "9093"
    networks:
      - monitoring
  line-notify:
    image: line-notify-image
    container_name: line-notify
    ports:
      - 8089:8080
    expose:
      - 8080
    networks:
      - monitoring

      

