groups:
  - name: monitoring-alerts
    rules:
      - alert: HighErrorRate
        expr: rate(http_requests_total{status="500"}[5m]) > 0.05
        for: 1m  # แจ้งเตือนถ้าอัตราการเกิดข้อผิดพลาดสูงเกิน 5% ติดต่อกัน 1 นาที
        labels:
          severity: critical
        annotations:
          summary: "High error rate detected"
          description: "The error rate is above 5% for the last 1 minute."

      - alert: InstanceDown
        expr: up == 0
        for: 5s  # แจ้งเตือนถ้า instance ล่มเกิน 30 วินาที
        labels:
          severity: critical
        annotations:
          summary: "Instance down"
          description: "The instance has been down for the last 1 minute."

      - alert: HighLatency
        expr: avg(rate(http_request_duration_seconds_sum[5m])) by (job) > 1
        for: 1m  # แจ้งเตือนถ้าความหน่วงเฉลี่ยของคำขอเกิน 1 วินาทีติดต่อกัน 1 นาที
        labels:
          severity: warning
        annotations:
          summary: "High request latency"
          description: "The average request duration is above 1 second for the last 1 minute."
