global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: "nextjs-metrics"
    static_configs:
      - targets:
        - 'example-nodejs-app:3000'
        labels:
          service: "nextjs-app"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert.rules.yml"
