global:
  scrape_interval: 15s  # ดึงข้อมูลทุก 15 วินาที

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "nextjs-metrics"
    static_configs:
      - targets:
        - 'https://7b90-49-231-1-82.ngrok-free.app/api/metrics'
        labels:
          service: "nextjs-app"
