global:
  scrape_interval: 1m  # ดึงข้อมูลเมตริกจากแหล่งข้อมูลที่กำหนดทุก ๆ 1 นาที
  evaluation_interval: 30s  # ทำการประเมินกฎการแจ้งเตือนหรือกฎการประเมินผลต่างๆ ทุก ๆ 30 วินาที

scrape_configs:
  - job_name: "nextjs-metrics"
    static_configs:
      - targets:
        - 'example-nodejs-app:3000'
        labels:
          service: "nextjs-app"

  - job_name: 'http-check'
    metrics_path: /probe
    params:
      module: [http_2xx]  # ตรวจสอบว่ามีการตอบกลับ HTTP status 2xx หรือไม่
    static_configs:
      - targets:
          - http://10.1.29.17:8090  # URL ที่ต้องการตรวจสอบ
          - http://10.1.29.17:4723  # URL ที่ต้องการตรวจสอบ
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # แทนที่ด้วยที่อยู่ของ Blackbox Exporter

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - "alert.rules.yml"
