
# global:
#   scrape_interval: 5s
# scrape_configs:
#   - job_name: "example-nodejs-app"
#     static_configs:
#       - targets:
#           - "10.1.29.12:8080"
#           - "example-nodejs-app2:8080"
#           - "10.1.29.22:3111"

#   - job_name: "project-docker-test"
#     static_configs:
#       - targets:
#           - "10.1.29.12:3001"
#     metrics_path: "/metrics"   


global:
  scrape_interval: 5s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"
rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "example-nodejs-app"
    static_configs:
      - targets: ['10.1.29.12:8080']
        labels:
          service: "example-nodejs-app"
          group: "example-nodejs-app"
  - job_name: "example-nodejs-app2"
    static_configs:
      - targets: ['10.1.29.12:8081']
        labels:
          service: "example-nodejs-app2"
          group: "example-nodejs-app2"


