global:
  scrape_interval: 15s  # ดึงข้อมูลทุก 15 วินาที

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - "alertmanager:9093"

rule_files:
  - alert.rules.yml

scrape_configs:
  - job_name: "nextjs-metrics"
    static_configs:
      - targets:
        - 'http://localhost:3001/api/metrics'
        labels:
          service: "nextjs-app"
# http://localhost:3001
# 'https://bcfe-115-31-145-24.ngrok-free.app/api/metrics'
